"""Copy to config_local.py and confirm the physical board before enabling."""

CIRCUITPYTHON_VERSION = "9.1.1"
HARDWARE_COMPATIBILITY_DECISION = "COMPATIBLE"
MAGTAG_REVISION = "ORIGINAL_MAGTAG_2.9"
DISPLAY_CONTROLLER = "UC8151D"
ENABLE_PHYSICAL_DISPLAY = False
PHYSICAL_TEST_MODE = "DISABLED"
ENABLE_UART_RECEIVER = False
UART_TEST_MODE = "DISABLED"
UART_RX_PIN_ALIAS = "D10"
UART_BAUD = 115200
UART_READ_BUDGET = 256
FULL_REFRESH_INTERVAL = 50
EVENT_QUEUE_CAPACITY = 128
MAX_LINES = 64
MAX_CHARS = 8192
