ENABLE_UART_TEST = False
UART_TEST_MODE = "DISABLED"
UART_TX_PIN_ALIAS = "A0"
UART_BAUD = 115200
INTER_FRAME_DELAY_SECONDS = 0.15
SCENARIO_DELAY_SECONDS = 4.5
STARTUP_DELAY_SECONDS = 3.0
ENABLE_BIDIRECTIONAL_UART_TEST = False
BIDIRECTIONAL_UART_TEST_MODE = "DISABLED"
UART_RX_PIN_ALIAS = "A1"
UART_READ_BUDGET = 256
UART_ACK_TEST_TIMEOUT_SECONDS = 60
UART_ACK_TRACKER_CAPACITY = 16
STATUS_HELLO_TIMEOUT_SECONDS = 5.0
FRAME_ACCEPTED_TIMEOUT_SECONDS = 3.0
REFRESH_STARTED_TIMEOUT_SECONDS = 8.0
REFRESH_COMPLETED_TIMEOUT_SECONDS = 15.0
DISPLAY_CAUGHT_UP_TIMEOUT_SECONDS = 18.0
ENABLE_EDITOR_INTEGRATION_TEST = False
EDITOR_INTEGRATION_TEST_MODE = "DISABLED"
EDITOR_EVENT_QUEUE_CAPACITY = 64
EDITOR_ACK_TRACKER_CAPACITY = 96
EDITOR_TEST_TIMEOUT_SECONDS = 240
ENABLE_USB_KEYBOARD_TEST = False
USB_KEYBOARD_TEST_MODE = "DISABLED"
USB_KEYBOARD_QUEUE_CAPACITY = 64
USB_KEYBOARD_ACK_TRACKER_CAPACITY = 128
USB_KEYBOARD_MAX_EVENTS = 500
# Bounded USB polling: at most four reports per loop, each with a short read
# timeout, so a silent keyboard never blocks display polling.
USB_KEYBOARD_POLL_BUDGET = 4
USB_KEYBOARD_READ_TIMEOUT_MS = 2
# Adaptive display pacing. These mirror magwrite_transport/pacing.py, which is
# the single source of truth and carries the measured panel numbers behind each
# value; a host test asserts the two agree. Fifty partial refreshes remains the
# binding physical ceiling.
USB_KEYBOARD_COALESCE_SECONDS = 0.25
USB_KEYBOARD_QUIET_SECONDS = 0.6
USB_KEYBOARD_CAUGHT_UP_MIN_SEND_SECONDS = 1.3
USB_KEYBOARD_SUSTAINED_MIN_SEND_SECONDS = 2.6
# "AUTO" identifies the keyboard from its USB descriptor and applies a recorded
# device layout if one matches; anything unrecognised gets standard HID.
USB_KEYBOARD_LAYOUT = "AUTO"
# A live run is operator-paced, so it is abandoned only after a long silence.
USB_KEYBOARD_IDLE_TIMEOUT_SECONDS = 600
USB_KEYBOARD_SESSION_TIMEOUT_SECONDS = 2700
